# Generated by Django 4.1.3 on 2023-01-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminend', '0003_admindb_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='workdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pic')),
            ],
        ),
    ]
