# Generated by Django 4.1.3 on 2023-01-30 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminend', '0007_consultdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='username',
            new_name='name',
        ),
    ]
